config = {
    "VERSION": "v0.1",
    "MAX_PLAYERS": 4,
    "TICK_WAIT_TIME": 0.05,
    "POPUP_COMMUNICATE_TIME": 2,
    "CONNECTION_TIMEOUT_TIME": 5,
    "HIGH_PORTS_BASE": 45402,
    "CONNECTION_UPKEEP_TIME_PERIOD": 1,
    "CONNECTION_UPKEEP_MISSED_CALLS_ALLOWED": 3
}
